#! /bin/bash

#######
# ADD THIS FILE TO THE HOST MACHINES /USR/BIN
# USAGE
# certbot add <domain> <email>
# certbot renew all
# certbot renew <domain>
# certbot info
# certbot update
#######

METHOD="$1"
DOMAIN="$2"
EMAIL="$3"

docker pull apld/certbot:latest

if [ "$METHOD" = "add" ]; then

  docker run -ti \
  -v /var/www/certs/:/etc/letsencrypt/ \
  -v /var/www/${DOMAIN}/httpdocs:/webroot/ \
  apld/certbot \
  add www.${DOMAIN} $EMAIL

elif [ "$METHOD" = "renew" ]; then

  if [ "$DOMAIN" = "all" ]; then

    for i in $(ls -d /var/www/certs/live/*); do

      certbot renew ${i##*/}

    done

  else

    docker run -ti \
    -v /var/log/letsencrypt/:/var/log/letsencrypt/ \
    -v /var/www/certs/:/etc/letsencrypt/ \
    -v /var/www/$DOMAIN/httpdocs:/webroot/ \
    apld/certbot \
    renew www.$DOMAIN

  fi

elif [ "$METHOD" = "info" ]; then

  docker run -ti \
  -v /var/www/certs/:/etc/letsencrypt/ \
  apld/certbot \
  info

elif [ "$METHOD" = "update" ]; then

  docker pull apld/certbot:latest

fi
