#! /bin/bash

METHOD="$1"

if [ "$METHOD" = "build" ]; then

  # base build
  docker build -t certbot -f cert/Dockerfile cert/

elif [ "$METHOD" = "push" ]; then

  # base push
  docker tag certbot apld/certbot
  docker push apld/certbot

elif [ "$METHOD" = "test" ]; then

  # base test <add|renew|info> <domain> <email>
  docker run -ti \
  -v /var/www/certs/:/etc/letsencrypt/ \
  -v /var/www/$3:/webroot/ \
  certbot \
  $2 $3 $4

fi
